image: node:latest
 
cache:
  paths:
  - node_modules/ 
  
stages:
  - deploy

install:
  stage: deploy
  environment:
    name: Fiddle.be
    url: https://sitbe.fiddle.be
  script:
    - npm install
    - npm run lint
    - npm run build
    - npm run deploy --user=$FTP_USER --pwd=$FTP_PASS
  artifacts:
    paths:
      - node_modules/
  only:
    - master
