image: node:latest
 
cache:
  paths:
  - node_modules/ 
  
stages:
  - qa
  - build
  - test
  - deploy

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

qa:
  stage: qa
  script: npm run lint

build:
  stage: build
  script: npm run build

test:
  stage: test
  script: npm run test

deploy:
  stage: deploy
  environment:
    name: Fiddle.be
    url: https://sitbe.fiddle.be
  script:
    - echo "using FTP to deploy the app"
    - npm run deploy --user=$FTP_USER --pwd=$FTP_PASS
  only:
    - master
